mapping = {
    'Altenstadt': ['Altenstadt', 'Heegheim', 'Höchst', 'Lindheim', 'Oberau', 'Rodenbach', 'Waldsiedlung', 'Enzheim'],
    'Bad Nauheim': ['Bad Nauheim', 'Rödgen', 'Schwalheim', 'Steinfurth', 'Wisselsheim'],
    'Bad Vilbel': ['Bad Vilbel', 'Dortelweil', 'Nieder Mörlen', 'Gronau', 'Heilsberg', 'Massenheim'],
    'Butzbach': ['Butzbach', 'Bodenrod', 'Ebersgöns', 'Griedel', 'Hausen-Oes', 'Hoch-Weisel', 'Kirch-Göns', 'Maibach', 'Münster', 'Nieder-Weisel', 'Ostheim', 'Fauerbach vor der Höhe', 'Pohl-Göns', 'Wiesental'],
    'Büdingen': ['Büdingen', 'Aulendiebach', 'Büches', 'Calbach', 'Diebach Am Haag', 'Dudenrod', 'Düdelsheim', 'Eckartshausen', 'Lorbach', 'Michelau', 'Orleshausen', 'Rinderbügen', 'Rohrbach', 'Vonhausen', 'Wolf', 'Wolferborn'],
    'Echzell': ['Echzell', 'Bingenheim', 'Bisses', 'Gettenau', 'Grund-Schwalheim'],
    'Florstadt': ['Florstadt', 'Leidhecken', 'Nieder-Florstadt', 'Nieder-Mockstadt', 'Ober-Florstadt', 'Staden', 'Stammheim'],
    'Friedberg (Hessen)': ['Friedberg (Hessen)', 'Frieberg', 'Bauernheim', 'Bruchenbrücken', 'Dorheim', 'Ockstadt', 'Ossenheim'],
    'Gedern': ['Gedern', 'Mittel-Seemen', 'Nieder-Seemen', 'Ober-Seemen', 'Steinberg', 'Wenings'],
    'Glauburg': ['Glauburg', 'Glauberg', 'Stockheim'],
    'Hirzenhain': ['Hirzenhain', 'Glashütten', 'Merkenfritz'],
    'Karben': ['Karben', 'Burg-Gräfenrode', 'Groß-Karben', 'Klein-Karben', 'Kloppenheim', 'Okarben', 'Petterweil', 'Rendel'],
    'Kefenrod': ['Kefenrod', 'Bindsachsen', 'Burgbracht', 'Helfersdorf', 'Hitzkirchen'],
    'Limeshain': ['Limeshain', 'Rommelhausen', 'Hainchen', 'Himbach'],
    'Münzenberg': ['Münzenberg', 'Gambach', 'Ober-Hörgern', 'Trais'],
    'Nidda': ['Nidda', 'Bad Salzhausen', 'Borsdorf', 'Eichelsdorf', 'Fauerbach', 'Fauerbach (Nidda)', 'Geiß-Nidda', 'Harb', 'Kohden', 'Michelnau', 'Ober-Lais', 'Ober-Schmitten', 'Ober-Widdersheim', 'Schwickartshausen', 'Stornfels', 'Ulfa', 'Unter-Schmitten', 'Unter-Widdersheim', 'Wallernhausen'],
    'Niddatal': ['Niddatal', 'Assenheim', 'Bönstadt', 'Ilbenstadt', 'Kaichen'],
    'Ober-Mörlen': ['Ober-Mörlen', 'Langenhain-Ziegenberg'],
    'Ortenberg': ['Ortenberg', 'Bergheim', 'Bleichenbach', 'Eckartsborn', 'Effolderbach', 'Gelnhaar', 'Lißberg', 'Selters', 'Usenborn', 'Wippenbach'],
    'Ranstadt': ['Ranstadt', 'Bellmuth', 'Bobenhausen', 'Dauernheim', 'Ober-Mockstadt'],
    'Reichelsheim (Wetterau)': ['Reichelsheim (Wetterau)', 'Reichelsheim', 'Beienheim', 'Blofeld', 'Dorn-Assenheim', 'Heuchelheim', 'Weckesheim'],
    'Rockenberg': ['Rockenberg', 'Oppershofen'],
    'Rosbach v. d. Höhe': ['Rosbach v. d. Höhe', 'Nieder-Rosbach', 'Ober-Rosbach v. d. H.', 'Rodheim v. d. H.'],
    'Wölfersheim': ['Wölfersheim', 'Berstadt', 'Melbach', 'Södel', 'Wohnbach'],
    'Wöllstadt': ['Wöllstadt', 'Nieder-Wöllstadt', 'Ober-Wöllstadt'],
}
