sorted_gebiet_to_gemeinde = {
    "Altenstadt": "Altenstadt",
    "Heegheim": "Altenstadt",
    "Höchst": "Altenstadt",
    "Lindheim": "Altenstadt",
    "Oberau": "Altenstadt",
    "Rodenbach": "Altenstadt",
    "Waldsiedlung": "Altenstadt",
    "Enzheim": "Altenstadt",
    "Bad Nauheim": "Bad Nauheim",
    "Rödgen": "Bad Nauheim",
    "Schwalheim": "Bad Nauheim",
    "Steinfurth": "Bad Nauheim",
    "Wisselsheim": "Bad Nauheim",
    "Bad Vilbel": "Bad Vilbel",
    "Dortelweil": "Bad Vilbel",
    "Nieder Mörlen": "Bad Vilbel",
    "Gronau": "Bad Vilbel",
    "Heilsberg": "Bad Vilbel",
    "Massenheim": "Bad Vilbel",
    "Bodenrod": "Butzbach",
    "Butzbach": "Butzbach",
    "Ebersgöns": "Butzbach",
    "Griedel": "Butzbach",
    "Hausen-Oes": "Butzbach",
    "Hoch-Weisel": "Butzbach",
    "Kirch-Göns": "Butzbach",
    "Maibach": "Butzbach",
    "Münster": "Butzbach",
    "Nieder-Weisel": "Butzbach",
    "Ostheim": "Butzbach",
    "Fauerbach vor der Höhe": "Butzbach",
    "Pohl-Göns": "Butzbach",
    "Wiesental": "Butzbach",
    "Aulendiebach": "Büdingen",
    "Büches": "Büdingen",
    "Büdingen": "Büdingen",
    "Calbach": "Büdingen",
    "Diebach Am Haag": "Büdingen",
    "Dudenrod": "Büdingen",
    "Düdelsheim": "Büdingen",
    "Eckartshausen": "Büdingen",
    "Lorbach": "Büdingen",
    "Michelau": "Büdingen",
    "Orleshausen": "Büdingen",
    "Rinderbügen": "Büdingen",
    "Rohrbach": "Büdingen",
    "Vonhausen": "Büdingen",
    "Wolf": "Büdingen",
    "Wolferborn": "Büdingen",
    "Bingenheim": "Echzell",
    "Bisses": "Echzell",
    "Echzell": "Echzell",
    "Gettenau": "Echzell",
    "Grund-Schwalheim": "Echzell",
    "Leidhecken": "Florstadt",
    "Nieder-Florstadt": "Florstadt",
    "Nieder-Mockstadt": "Florstadt",
    "Ober-Florstadt": "Florstadt",
    "Staden": "Florstadt",
    "Stammheim": "Florstadt",
    "Bauernheim": "Friedberg (Hessen)",
    "Frieberg": "Friedberg (Hessen)",
    "Bruchenbrücken": "Friedberg (Hessen)",
    "Dorheim": "Friedberg (Hessen)",
    "Ockstadt": "Friedberg (Hessen)",
    "Ossenheim": "Friedberg (Hessen)",
    "Gedern": "Gedern",
    "Mittel-Seemen": "Gedern",
    "Nieder-Seemen": "Gedern",
    "Ober-Seemen": "Gedern",
    "Steinberg": "Gedern",
    "Wenings": "Gedern",
    "Glauberg": "Glauburg",
    "Stockheim": "Glauburg",
    "Glashütten": "Hirzenhain",
    "Hirzenhain": "Hirzenhain",
    "Merkenfritz": "Hirzenhain",
    "Burg-Gräfenrode": "Karben",
    "Groß-Karben": "Karben",
    "Klein-Karben": "Karben",
    "Kloppenheim": "Karben",
    "Okarben": "Karben",
    "Petterweil": "Karben",
    "Rendel": "Karben",
    "Bindsachsen": "Kefenrod",
    "Burgbracht": "Kefenrod",
    "Helfersdorf": "Kefenrod",
    "Hitzkirchen": "Kefenrod",
    "Kefenrod": "Kefenrod",
    "Rommelhausen": "Limeshain",
    "Hainchen": "Limeshain",
    "Himbach": "Limeshain",
    "Gambach": "Münzenberg",
    "Münzenberg": "Münzenberg",
    "Ober-Hörgern": "Münzenberg",
    "Trais": "Münzenberg",
    "Bad Salzhausen": "Nidda",
    "Borsdorf": "Nidda",
    "Eichelsdorf": "Nidda",
    "Fauerbach": "Nidda",
    "Geiß-Nidda": "Nidda",
    "Harb": "Nidda",
    "Kohden": "Nidda",
    "Michelnau": "Nidda",
    "Nidda": "Nidda",
    "Ober-Lais": "Nidda",
    "Ober-Schmitten": "Nidda",
    "Ober-Widdersheim": "Nidda",
    "Schwickartshausen": "Nidda",
    "Stornfels": "Nidda",
    "Ulfa": "Nidda",
    "Unter-Schmitten": "Nidda",
    "Unter-Widdersheim": "Nidda",
    "Fauerbach (Nidda)": "Nidda",
    "Wallernhausen": "Nidda",
    "Assenheim": "Niddatal",
    "Bönstadt": "Niddatal",
    "Ilbenstadt": "Niddatal",
    "Kaichen": "Niddatal",
    "Langenhain-Ziegenberg": "Ober-Mörlen",
    "Ober-Mörlen": "Ober-Mörlen",
    "Bergheim": "Ortenberg",
    "Bleichenbach": "Ortenberg",
    "Eckartsborn": "Ortenberg",
    "Effolderbach": "Ortenberg",
    "Gelnhaar": "Ortenberg",
    "Lißberg": "Ortenberg",
    "Ortenberg": "Ortenberg",
    "Selters": "Ortenberg",
    "Usenborn": "Ortenberg",
    "Wippenbach": "Ortenberg",
    "Bellmuth": "Ranstadt",
    "Bobenhausen I": "Ranstadt",
    "Dauernheim": "Ranstadt",
    "Ober-Mockstadt": "Ranstadt",
    "Ranstadt": "Ranstadt",
    "Beienheim": "Reichelsheim (Wetterau)",
    "Blofeld": "Reichelsheim (Wetterau)",
    "Dorn-Assenheim": "Reichelsheim (Wetterau)",
    "Heuchelheim": "Reichelsheim (Wetterau)",
    "Reichelsheim": "Reichelsheim (Wetterau)",
    "Weckesheim": "Reichelsheim (Wetterau)",
    "Oppershofen": "Rockenberg",
    "Rockenberg": "Rockenberg",
    "Nieder-Rosbach": "Rosbach v. d. Höhe",
    "Ober-Rosbach v. d. H.": "Rosbach v. d. Höhe",
    "Rodheim v. d. H.": "Rosbach v. d. Höhe",
    "Berstadt": "Wölfersheim",
    "Melbach": "Wölfersheim",
    "Södel": "Wölfersheim",
    "Wohnbach": "Wölfersheim",
    "Wölfersheim": "Wölfersheim",
    "Nieder-Wöllstadt": "Wöllstadt",
    "Ober-Wöllstadt": "Wöllstadt"
}
